name: Deploy to Firebase Hosting
on:
  push:
    branches: [ "main" ]
concurrency:
  group: elvis-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  building:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn && yarn build
  deploying:
    runs-on: ubuntu-22.04
    needs: building
    steps:
      # - uses: actions/checkout@v2
      - name: Show files
        run: ls -la
        # uses: w9jds/firebase-action@master
        # with:
        #   args: deploy --only hosting
        # env:
        #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  # deploy:
  #   runs-on: ubuntu-22-04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy with Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}