name: Deploy to Firebase Hosting
on:
  push:
    branches: [ "main" ]
jobs:
  exploring:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Show node version
        run: node --version
  # deploy:
  #   runs-on: ubuntu-22-04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy with Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}