name: Probando cosas
on:
  push:
    branches: [ "main" ]
jobs:
  exploring:
    runs-on: ubuntu-22-04
    steps:
      - name: Haciendo el paso 1
        run: echo "Hello, world!"
      - name: Haciendo el paso 2
        run: ls -la
      - name: Haciendo el paso 3
        run: pwd
  # deploy:
  #   runs-on: ubuntu-22-04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy with Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}