name: Deploy to Firebase Hosting
on:
  push:
    tags:
      - 'deploy'
concurrency:
  group: elvis-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  building:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn && yarn build
      - name: Copy firebase files to dist
        run: cp firebase.json dist/

      - name : Upload dist folder on artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./dist

  deploying:
    runs-on: ubuntu-22.04
    needs: building
    steps:
      - name: Updating node for version 20.0.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0'
      
      -  name: Install Firebase CLI
         run: yarn global add firebase-tools && firebase --version 
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT }}  



        # with:
        #   args: deploy --only hosting
        # env:
        #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  # deploy:
  #   runs-on: ubuntu-22-04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy with Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}